[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
# QEMUを起動
#   -machine virt     = virtマシンとして起動する
#   -bios default     = デフォルトのBIOS (ここではOpenSBI) を使用する
#   -nographic        = QEMUをウィンドウなしで起動する
#   -serial mon:stdio = QEMUの標準入出力を仮想マシンのシリアルポートに接続する
#   --no-reboot       = 仮想マシンがクラッシュしたら、再起動せずに停止させる (デバッグに便利)
#
#   -d unimp,guest_errors,int,cpu_reset = デバッグログ有効化
#   -D qemu.log                         = デバッグ情報を`qemu.log`というファイルに出力
runner = "qemu-system-riscv32 -machine virt -bios default -nographic -serial mon:stdio --no-reboot -d unimp,guest_errors,int,cpu_reset -D qemu.log -kernel"
rustflags = [
  # https://doc.rust-lang.org/rustc/codegen-options/index.html
  "-C", "link-arg=-Tuser.ld",
  "-C", "link-arg=-Map=user.map",
]
